### ISSUE TITLE
Errors when running typepad.client.interactive_authorize

### ISSUE THREAD

**Issue by sfermigier** [typepad/python-typepad-api#2]
Here's the result of trying to follow the tutorial here http://sixapart.github.com/python-typepad-api/tut/auth.html (with my own keys of course):

```
(env)Stefanes-macbook% virtualenv env
New python executable in env/bin/python
Installing setuptools............................done.
(env)Stefanes-macbook% . ./env/bin/activate
(env)Stefanes-macbook% pip install -I typepad
 Downloading/unpacking typepad
   Downloading typepad-2.0.tar.gz (82Kb): 82Kb downloaded
   Running setup.py egg_info for package typepad

Downloading/unpacking oauth>=1.0.1 (from typepad)
  Downloading oauth-1.0.1.tar.gz
  Running setup.py egg_info for package oauth

Downloading/unpacking remoteobjects==1.1.1 (from typepad)
  Downloading remoteobjects-1.1.1.tar.gz
  Running setup.py egg_info for package remoteobjects

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.gitignore' found anywhere in distribution
    no previously-included directories found matching '.git'
    no previously-included directories found matching 'dist'
Downloading/unpacking batchhttp==1.1.1 (from typepad)
  Downloading batchhttp-1.1.1.tar.gz
  Running setup.py egg_info for package batchhttp

Downloading/unpacking simplejson>=2.0.0 (from remoteobjects==1.1.1->typepad)
  Downloading simplejson-2.1.6.tar.gz (52Kb): 52Kb downloaded
  Running setup.py egg_info for package simplejson

Downloading/unpacking httplib2>=0.5.0 (from remoteobjects==1.1.1->typepad)
  Downloading httplib2-0.7.1.tar.gz (84Kb): 84Kb downloaded
  Running setup.py egg_info for package httplib2

Installing collected packages: batchhttp, httplib2, oauth, remoteobjects, simplejson, typepad
  Running setup.py install for batchhttp

  Running setup.py install for httplib2

  Running setup.py install for oauth

  Running setup.py install for remoteobjects

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.gitignore' found anywhere in distribution
    no previously-included directories found matching '.git'
    no previously-included directories found matching 'dist'
  Running setup.py install for simplejson
    building 'simplejson._speedups' extension
    /usr/bin/cc -fno-strict-aliasing -O3 -march=core2 -msse4.1 -w -pipe -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/fermigier/homebrew/Cellar/python/2.7.1/include/python2.7 -c simplejson/_speedups.c -o build/temp.macosx-10.4-x86_64-2.7/simplejson/_speedups.o
    /usr/bin/cc -L/Users/fermigier/homebrew/Cellar/readline/6.1/lib -L/Users/fermigier/homebrew/lib -bundle -undefined dynamic_lookup -L/Users/fermigier/homebrew/Cellar/readline/6.1/lib -L/Users/fermigier/homebrew/lib build/temp.macosx-10.4-x86_64-2.7/simplejson/_speedups.o -o build/lib.macosx-10.4-x86_64-2.7/simplejson/_speedups.so

  Running setup.py install for typepad

Successfully installed batchhttp httplib2 oauth remoteobjects simplejson typepad
Cleaning up...
(env)Stefanes-macbook% python src/test.py    
<typepad.api.User object at 0x1011de990>
{'_location': 'http://api.typepad.com/users/sf@nuxeo.com.json', 'api_data': {}, '_http': <typepad.tpclient.ThreadAwareTypePadClientProxy object at 0x10118c610>, '_delivered': False, 'batch_requests': True, '_origin': ('/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/typepad/api.py', 2096, 'get_by_url_id'), 'url_id': 'sf@nuxeo.com', 'id': 'tag:api.typepad.com,2009:sf@nuxeo.com'}
<typepad.tpobject._streams.StreamOfEvent object at 0x101234390>
To join your application 'Nuxeo Test', follow this link and click "Allow":

<https://www.typepad.com/secure/services/api/6p01543351e4bf970c/oauth-approve?oauth_token=XXX>

Enter the verifier code TypePad gave you: XXX
Traceback (most recent call last):
  File "src/test.py", line 26, in <module>
    access_token = typepad.client.interactive_authorize(consumer, app)
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/typepad/tpclient.py", line 223, in interactive_authorize
    typepad.client.complete_batch()
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/batchhttp/client.py", line 623, in complete_batch
    self.batchrequest.process(self, self.endpoint)
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/batchhttp/client.py", line 453, in process
    headers, body = self.construct(http)
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/batchhttp/client.py", line 475, in construct
    submsg = request.as_message(http, request_id)
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/batchhttp/client.py", line 339, in as_message
    headers, body = self._update_headers_from_cache(http)
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/batchhttp/client.py", line 264, in _update_headers_from_cache
    http.request(**objreq)
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/typepad/tpclient.py", line 388, in request
    return super(TypePadClient, self).request(uri, method, body, headers, redirections, connection_type)
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/batchhttp/client.py", line 668, in request
    response, content = super(BatchClient, self).request(uri, method, body, headers, redirections, connection_type)
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/httplib2/__init__.py", line 1436, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/httplib2/__init__.py", line 1188, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/fermigier/projects/tdn/env/lib/python2.7/site-packages/httplib2/__init__.py", line 1122, in _conn_request
    if conn.sock is None:
AttributeError: 'CaptureHTTPConnection' object has no attribute 'sock'
```

**Comment by markpasc** [comment]
Hmm, that probably means that version of `httplib2` is too new to work with the `typepad` module code as written. You should be able to work around it by downgrading `httplib2` (the `requirements.txt` file asks for 0.5.0 so you might try that version).
